### ISSUE TITLE
bots unable to initialize at citadel buildings

### ISSUE THREAD

**Issue by royluo1984** [CyberTech/EVEBot#8]
bots unable to initial at citadel buildings and also unable to move items into compressation array.

I tried reinstall lavish, isxeve and get a brand new version of evebot by using git clone, but the problems are still the same.

you can see my folders via images below
https://drive.google.com/file/d/0B7foVXfJdienRGo4X3lXYnI3cHM/view?usp=sharing
https://drive.google.com/file/d/0B7foVXfJdienb240cVVyWUROamc/view?usp=sharing

**Comment by royluo1984** [comment]
I am willing to pay for this update

**Comment by royluo1984** [comment]
I still receive errors below when I docking in a CITADEL (astrahus) and engineering complex -raitaru
(havn't try other citadel type)

Error:No such 'item' member 'TypeID' @${MyShip.ToItem.TypeID}
ISXEVE: itemtype Failed ItemInfo inheritanceB: 1023696000979
Error:No such 'item' member 'GroupID' @${MyShip.ToItem.GroupID}
ISXEVE: itemtype Failed ItemInfo inheritanceB: 1023696000979
Error:No such 'item' member 'TypeID' @${MyShip.ToItem.TypeID}
ISXEVE: itemtype Failed ItemInfo inheritanceB: 1023696000979
Error:No such 'item' member 'GroupID' @${MyShip.ToItem.GroupID}
ISXEVE: itemtype Failed ItemInfo inheritanceB: 1023696000979
Error:No such 'item' member 'TypeID' @${MyShip.ToItem.TypeID}
ISXEVE: itemtype Failed ItemInfo inheritanceB: 1023696000979
Error:No such 'item' member 'GroupID' @${MyShip.ToItem.GroupID}
ISXEVE: itemtype Failed ItemInfo inheritanceB: 1023696000979
Error:No such 'item' member 'TypeID' @${MyShip.ToItem.TypeID}

**Comment by royluo1984** [comment]
When my miner trying store ores into compression array  in space, 

the script is able to locate and open the compression array but it will repeatedly give **in-game** error like you cannot move items into that location

the error messages given by the console are list below
ISXEVE: eveinvchildwindow.UsedCapacity Inventory not yet available
ISXEVE: eveinvchildwindow.Capacity Inventory not yet available
ISXEVE: eveinvchildwindow.UsedCapacity Inventory not yet available
ISXEVE: eveinvchildwindow.UsedCapacity Inventory not yet available
ISXEVE: eveinvchildwindow.Capacity Inventory not yet available
ISXEVE: eveinvchildwindow.UsedCapacity Inventory not yet available
ISXEVE: eveinvchildwindow.UsedCapacity Inventory not yet available
ISXEVE: eveinvchildwindow.Capacity Inventory not yet available


FYI, the delivery option "hangar arrary" works perfectly

**Comment by royluo1984** [comment]
I tried reinstall lavish, isxeve and get a brand new version of evebot by using git clone, but the problems are still the same.

you can see my folders via images below
https://drive.google.com/file/d/0B7foVXfJdienRGo4X3lXYnI3cHM/view?usp=sharing 
https://drive.google.com/file/d/0B7foVXfJdienb240cVVyWUROamc/view?usp=sharing

**Comment by CyberTech** [comment]
This was resolved a few months ago.
